
import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Packer,
  HorizontalPositionAlign,
  VerticalPositionAlign,
  HorizontalPosition,
  VerticalPosition,
  TextWrappingType,
  TextWrappingSide,
} from 'docx';
import type { GetResumeFeedbackOutput } from '@/ai/flows/resume-feedback-tool';

type ResumeData = GetResumeFeedbackOutput['rewrittenResume'];

export function createResumeDocx(resumeData: ResumeData): Document {
  const { name, title, contact, summary, experience, education, projects, skills, keyAchievements, training } = resumeData;

  const doc = new Document({
    creator: "AI Mentor",
    title: `Resume for ${name}`,
    description: `A resume for ${name} generated by AI Mentor.`,
    styles: {
        paragraphStyles: [
            {
                id: 'Normal',
                name: 'Normal',
                basedOn: 'Normal',
                next: 'Normal',
                quickFormat: true,
                run: {
                    font: 'Calibri',
                    size: 22, // 11pt
                },
                 paragraph: {
                    spacing: { after: 100, line: 276 }, // 1.15 line spacing
                },
            },
            {
                id: 'Header',
                name: 'Header',
                basedOn: 'Normal',
                run: {
                    size: 20, // 10pt
                    color: '555555'
                }
            },
            {
                id: 'SectionTitle',
                name: 'Section Title',
                basedOn: 'Normal',
                next: 'Normal',
                quickFormat: true,
                run: {
                    size: 20, // 10pt
                    bold: true,
                    allCaps: true,
                    color: '555555'
                },
                paragraph: {
                     border: { bottom: { color: 'auto', space: 1, value: 'single', size: 4 } }, // 0.5pt
                     spacing: { after: 100, before: 200 },
                }
            },
        ]
    },
    sections: [{
      properties: {
        page: {
            margin: {
                top: '0.5in',
                right: '0.7in',
                bottom: '0.5in',
                left: '0.7in',
            },
        },
      },
      children: [
        new Paragraph({
          text: name.toUpperCase(),
          style: 'Title',
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          text: title,
          alignment: AlignmentType.CENTER,
          spacing: {after: 50}
        }),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            style: 'Header',
            children: [
                ...(contact.phone ? [new TextRun(`${contact.phone} | `)] : []),
                ...(contact.email ? [new TextRun(`${contact.email} | `)] : []),
                ...(contact.location ? [new TextRun(`${contact.location} | `)] : []),
                ...(contact.linkedin ? [new TextRun({ text: 'linkedin.com', style: "Hyperlink" })] : []),
            ],
            spacing: {after: 200}
        }),

        // Summary
        new Paragraph({
          text: 'Summary',
          style: 'SectionTitle',
        }),
        new Paragraph({ text: summary, style: 'Normal' }),

        // Experience
        new Paragraph({
          text: 'Experience',
          style: 'SectionTitle',
        }),
        ...experience.flatMap(exp => [
          new Paragraph({
            children: [
              new TextRun({ text: exp.title, bold: true, size: 22 }),
              new TextRun({ text: `\t${exp.dates}`, size: 20, color: '555555' }),
            ]
          }),
          new Paragraph({
             children: [
              new TextRun({ text: exp.company, bold: true, size: 22, color: '4A90E2' }), // Blue color
              new TextRun({ text: `\t${exp.location}`, size: 20, color: '555555' }),
            ]
          }),
          ...exp.bullets.map(bullet => new Paragraph({ text: bullet, bullet: { level: 0 }, style: 'Normal' })),
           new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),

        // Education
        new Paragraph({
          text: 'Education',
          style: 'SectionTitle',
        }),
         ...education.flatMap(edu => [
            new Paragraph({
                children: [
                    new TextRun({ text: edu.degree, bold: true, size: 22 }),
                    new TextRun({ text: `\t${edu.dates}`, size: 20, color: '555555'}),
                ]
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: edu.school, bold: true, size: 22, color: '4A90E2' }), // Blue color
                    new TextRun({ text: `\t${edu.location}`, size: 20, color: '555555'}),
                ]
            }),
            new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),
        
        // Linear sections for ATS compatibility
        new Paragraph({
          text: 'Skills',
          style: 'SectionTitle',
        }),
        new Paragraph({ text: skills.join(', '), style: 'Normal' }),

        // Projects
        new Paragraph({
          text: 'Projects',
          style: 'SectionTitle',
        }),
        ...projects.flatMap(proj => [
            new Paragraph({ text: proj.title, bold: true, size: 22 }),
            new Paragraph({ text: proj.description, style: 'Normal' }),
            ...(proj.link ? [new Paragraph({ children: [new TextRun({ text: proj.link, style: 'Hyperlink' })]})] : []),
             new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),
      ],
    }],
  });

  return doc;
}

