
import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Packer,
  HorizontalPositionAlign,
  VerticalPositionAlign,
  HorizontalPosition,
  VerticalPosition,
  TextWrappingType,
  TextWrappingSide,
} from 'docx';
import type { GetResumeFeedbackOutput } from '@/ai/flows/resume-feedback-tool';

type ResumeData = GetResumeFeedbackOutput['rewrittenResume'];

export function createResumeDocx(resumeData: ResumeData): Document {
  const { name, title, contact, summary, experience, education, projects, skills, keyAchievements, training } = resumeData;

  const doc = new Document({
    creator: "AI Mentor",
    title: `Resume for ${name}`,
    description: `A resume for ${name} generated by AI Mentor.`,
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          text: name,
          heading: HeadingLevel.TITLE,
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          text: title,
          style: 'Subtitle',
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
                ...(contact.email ? [new TextRun({ text: `${contact.email} | `, size: 20 })] : []),
                ...(contact.phone ? [new TextRun({ text: `${contact.phone} | `, size: 20 })] : []),
                ...(contact.location ? [new TextRun({ text: `${contact.location} | `, size: 20 })] : []),
                ...(contact.linkedin ? [new TextRun({ text: 'LinkedIn | ', link: contact.linkedin, style: "Hyperlink", size: 20 })] : []),
                ...(contact.github ? [new TextRun({ text: 'GitHub', link: contact.github, style: "Hyperlink", size: 20 })] : []),
            ],
        }),
        new Paragraph({ text: '', border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } }, spacing: { after: 200 } }), // spacer

        // Summary
        new Paragraph({
          text: 'Summary',
          heading: HeadingLevel.HEADING_1,
          border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } },
        }),
        new Paragraph({ text: summary, style: 'Normal' }),
        new Paragraph({ text: '', spacing: { after: 200 } }),

        // Experience
        new Paragraph({
          text: 'Experience',
          heading: HeadingLevel.HEADING_1,
          border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } },
        }),
        ...experience.flatMap(exp => [
          new Paragraph({
            children: [
              new TextRun({ text: exp.title, bold: true, size: 24 }),
              new TextRun({ text: `\t${exp.dates}`, size: 20, color: '555555' }),
            ]
          }),
          new Paragraph({
             children: [
              new TextRun({ text: `${exp.company}${exp.location ? ', ' + exp.location : ''}`, italics: true, size: 22 }),
            ]
          }),
          ...exp.bullets.map(bullet => new Paragraph({ text: bullet, bullet: { level: 0 } })),
           new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),

        // Education
        new Paragraph({
          text: 'Education',
          heading: HeadingLevel.HEADING_1,
          border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } },
        }),
         ...education.flatMap(edu => [
            new Paragraph({
                children: [
                    new TextRun({ text: edu.degree, bold: true, size: 24 }),
                    new TextRun({ text: `\t${edu.dates}`, size: 20, color: '555555'}),
                ]
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: `${edu.school}${edu.location ? ', ' + edu.location : ''}`, italics: true, size: 22 }),
                ]
            }),
            new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),
        
        // This is a simplified way to represent columns in DOCX. A true two-column layout is more complex.
        // It's better for ATS to list these sections linearly.
        new Paragraph({
          text: 'Skills',
          heading: HeadingLevel.HEADING_1,
          border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } },
        }),
        new Paragraph({ text: skills.join(', '), style: 'Normal' }),
        new Paragraph({ text: '', spacing: { after: 200 } }),

        // Projects
        new Paragraph({
          text: 'Projects',
          heading: HeadingLevel.HEADING_1,
          border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } },
        }),
        ...projects.flatMap(proj => [
            new Paragraph({ text: proj.title, style: 'Heading3' }),
            new Paragraph({ text: proj.description, style: 'Normal' }),
            ...(proj.link ? [new Paragraph({ children: [new TextRun({ text: proj.link, style: 'Hyperlink' })]})] : []),
             new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),

        // Key Achievements
        ...(keyAchievements && keyAchievements.length > 0 ? [
            new Paragraph({
              text: 'Key Achievements',
              heading: HeadingLevel.HEADING_1,
              border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } },
            }),
            ...keyAchievements.flatMap(ach => [
                new Paragraph({ text: ach.title, style: 'Heading3' }),
                new Paragraph({ text: ach.description, style: 'Normal' }),
                new Paragraph({ text: '', spacing: { after: 100 } }),
            ]),
        ] : []),

         // Training
        ...(training && training.length > 0 ? [
            new Paragraph({
              text: 'Training & Courses',
              heading: HeadingLevel.HEADING_1,
              border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } },
            }),
            ...training.flatMap(t => [
                new Paragraph({ text: t.title, style: 'Heading3' }),
                new Paragraph({ text: t.description, style: 'Normal' }),
                new Paragraph({ text: '', spacing: { after: 100 } }),
            ]),
        ] : []),

      ],
    }],
  });

  return doc;
}
