
import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Packer,
  HorizontalPositionAlign,
  VerticalPositionAlign,
  HorizontalPosition,
  VerticalPosition,
  TextWrappingType,
  TextWrappingSide,
  TabStopType,
  TabStopPosition,
} from 'docx';
import type { GetResumeFeedbackOutput } from '@/ai/flows/resume-feedback-tool';

type ResumeData = GetResumeFeedbackOutput['rewrittenResume'];

export function createResumeDocx(resumeData: ResumeData): Document {
  const { name, title, contact, summary, experience, education, projects, skills, keyAchievements, training } = resumeData;

  const doc = new Document({
    creator: "AI Mentor",
    title: `Resume for ${name}`,
    description: `A resume for ${name} generated by AI Mentor.`,
    styles: {
        paragraphStyles: [
            {
                id: 'Normal',
                name: 'Normal',
                basedOn: 'Normal',
                next: 'Normal',
                quickFormat: true,
                run: {
                    font: 'Calibri',
                    size: 22, // 11pt
                },
                 paragraph: {
                    spacing: { after: 100, line: 276 }, // 1.15 line spacing
                },
            },
            {
                id: 'Header',
                name: 'Header',
                basedOn: 'Normal',
                run: {
                    size: 20, // 10pt
                    color: '555555'
                },
                paragraph: {
                    alignment: AlignmentType.CENTER,
                    spacing: {after: 50}
                }
            },
            {
                id: 'SectionTitle',
                name: 'Section Title',
                basedOn: 'Normal',
                next: 'Normal',
                quickFormat: true,
                run: {
                    size: 24, // 12pt
                    bold: true,
                    allCaps: true,
                    color: '000000'
                },
                paragraph: {
                     border: { bottom: { color: 'auto', space: 1, value: 'single', size: 6 } }, // 0.75pt
                     spacing: { after: 100, before: 200 },
                }
            },
             {
                id: 'JobTitle',
                name: 'Job Title',
                basedOn: 'Normal',
                run: {
                    bold: true,
                    size: 22
                }
            },
            {
                id: 'Company',
                name: 'Company',
                basedOn: 'Normal',
                run: {
                    bold: true,
                    color: '4A90E2', // Blue color
                    size: 22
                }
            }
        ]
    },
    sections: [{
      properties: {
        page: {
            margin: {
                top: '0.5in',
                right: '0.7in',
                bottom: '0.5in',
                left: '0.7in',
            },
        },
      },
      children: [
        new Paragraph({
          text: name.toUpperCase(),
          style: 'Title',
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          text: title,
          alignment: AlignmentType.CENTER,
          spacing: {after: 50}
        }),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            style: 'Header',
            children: [
                ...(contact.phone ? [new TextRun(`${contact.phone} | `)] : []),
                ...(contact.email ? [new TextRun(`${contact.email} | `)] : []),
                ...(contact.location ? [new TextRun(`${contact.location} | `)] : []),
                ...(contact.linkedin ? [new TextRun({ text: `linkedin.com/in/profile`, style: "Hyperlink" }), new TextRun(' | ')] : []),
                ...(contact.github ? [new TextRun({ text: 'github.com/profile', style: "Hyperlink" })] : []),
            ].slice(0, -1), // Remove trailing separator
            spacing: {after: 200}
        }),

        // Summary
        new Paragraph({
          text: 'Summary',
          style: 'SectionTitle',
        }),
        new Paragraph({ text: summary, style: 'Normal' }),

        // Experience
        new Paragraph({
          text: 'Experience',
          style: 'SectionTitle',
        }),
        ...experience.flatMap(exp => [
          new Paragraph({
            style: 'JobTitle',
            children: [ new TextRun(exp.title) ],
          }),
          new Paragraph({
             children: [
              new TextRun({ text: exp.company, style: 'Company' }),
              new TextRun({ text: `\t${exp.dates} | ${exp.location}`, style: 'Header' }),
            ],
            tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }]
          }),
          ...exp.bullets.map(bullet => new Paragraph({ text: bullet, bullet: { level: 0 }, style: 'Normal' })),
           new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),

        // Education
        new Paragraph({
          text: 'Education',
          style: 'SectionTitle',
        }),
         ...education.flatMap(edu => [
            new Paragraph({
                children: [
                    new TextRun({ text: edu.degree, style: 'JobTitle' }),
                ],
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: edu.school, style: 'Company' }),
                    new TextRun({ text: `\t${edu.dates} | ${edu.location}`, style: 'Header' }),
                ],
                 tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }]
            }),
            new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),
        
        // Linear sections for ATS compatibility
        new Paragraph({
          text: 'Skills',
          style: 'SectionTitle',
        }),
        new Paragraph({ text: skills.join(', '), style: 'Normal' }),

        // Projects
        new Paragraph({
          text: 'Projects',
          style: 'SectionTitle',
        }),
        ...projects.flatMap(proj => [
            new Paragraph({ text: proj.title, style: 'JobTitle' }),
            new Paragraph({ text: proj.description, style: 'Normal' }),
            ...(proj.link ? [new Paragraph({ children: [new TextRun({ text: proj.link, style: 'Hyperlink' })]})] : []),
             new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),
         // Achievements
        new Paragraph({
          text: 'Key Achievements',
          style: 'SectionTitle',
        }),
        ...keyAchievements.flatMap(ach => [
            new Paragraph({ text: ach.title, style: 'JobTitle' }),
            new Paragraph({ text: ach.description, style: 'Normal' }),
             new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),
         // Training
        new Paragraph({
          text: 'Training / Courses',
          style: 'SectionTitle',
        }),
        ...training.flatMap(course => [
            new Paragraph({ text: course.title, style: 'JobTitle' }),
            new Paragraph({ text: course.description, style: 'Normal' }),
             new Paragraph({ text: '', spacing: { after: 100 } }),
        ]),
      ],
    }],
  });

  return doc;
}
